### ISSUE TITLE
Random Tier List Save File Corruption

### ISSUE THREAD

**Issue by gunchapred** [Eskuero/fehbuilder#11]
As the title suggests, at random, the save for one of my tier lists will get corrupted. It will make all tiers white, erase all their text, and reformat the text so that it will not display properly. Sometimes, it only happens to 1 or 2 tiers, but most of the time it happens to all of them. I am unsure what causes, especially as the trigger isn't exactly consistent.

Steps To Reproduce

- Make a tier list.
- Save it in a slot that isn't Default
- Leave and come back or refresh the page.
- Load the tier list again.

At pure random, this bug will occur, and seemingly not generating an error with  the console. IDK if it's because of the edits I make in-between saves or what, but this does keep happening.

Edit: It did produce an error, here it is.

![image](https://user-images.githubusercontent.com/56003719/154780178-6974949f-9cb8-41f5-8842-14da2617e7aa.png)

**Comment by Eskuero** [comment]
Related to the grammarly bug.
