### ISSUE TITLE
Innaccuracy War God Thorr stat

### ISSUE THREAD

**Issue by Laefrick** [Eskuero/fehbuilder#13]
I tried to experimental build on Thorr since the Arcane Axe will be coming soon, but the stat on the builder are not accurate and different from my current Thorr.

Please fix this issues

**Comment by Eskuero** [comment]
Fixed in https://github.com/Eskuero/fehbuilder/commit/8b6904e7e6fd2c643d34c2ae10d84c4db45df48c

**Comment by Laefrick** [comment]
Fixed thx
