### ISSUE TITLE
AR Blessings cap

### ISSUE THREAD

**Issue by Marbels** [Eskuero/fehbuilder#6]
currently for defense blessings, theyre still capped at 5. could you make it so that if using Seiros/Nott that it allows you to use a 6th blessing in the calc?
basically so i can recreate this image https://cdn.discordapp.com/attachments/537420602466762772/868217810080366633/Screenshot_20210723-124724.png

**Comment by Eskuero** [comment]
Fixed on https://github.com/Eskuero/fehbuilder/commit/d245a595a6847039a39ae0d55a76bb27dd4ba37d

The patch is already deployed. Make sure to refresh your browser with Ctrl+F5
