### ISSUE TITLE
Res Stat Miscalculation

### ISSUE THREAD

**Issue by LJBrooke** [Eskuero/fehbuilder#7]
Hi there

Just wanted to bring to your attention a mismatch between an in game res stat and the res shown by the Unit builder.

I'm checking my Units stats from the edit teams screen to stop invisible buffs applying.

The Wing Sword refine in both cases is the flashing Blades ability if you wish to recreate this.

![Screenshot_20210807-014839](https://user-images.githubusercontent.com/46628556/128580632-d15d164c-4ecc-427e-8c5c-23246902c057.jpg)

This is my in game stat screen with 40 res. And now recreating the hero in unit builder

![image](https://user-images.githubusercontent.com/46628556/128580592-70639fa4-88e7-4fdd-84c5-bb6c4c67813d.png)

Thanks for all the hard work!

**Comment by Eskuero** [comment]
The picture of Unit builder you uploaded is not my unit builder but fehstuff's custom unit builder which I have no control over
This is how it looks on mine which as you can see matches your in-game content
![image](https://user-images.githubusercontent.com/1757242/128611573-d50c4b5d-a081-451e-aa01-c2769675167f.png)

**Comment by LJBrooke** [comment]
Apologies, thanks
