### ISSUE TITLE
Tier List Download gives empty text file.

### ISSUE THREAD

**Issue by gunchapred** [Eskuero/fehbuilder#8]
Steps To Reproduce:

1. Go to the tier list editor.
2. Make a tier list.
3. Attempt to download it.

When this done, instead of downloading the tier list, you wind up downloading an empty text file instead.

Expected Outcome: Downloading the tier list in the form of an image.

**Comment by Eskuero** [comment]
Can you tell me which browser, device and operative system are you using? I can't reproduce without that info. My own systems seem to work fine

**Comment by gunchapred** [comment]
> Can you tell me which browser, device and operative system are you using? I can't reproduce without that info. My own systems seem to work fine

Chrome, on my Laptop, Windows.

**Comment by gunchapred** [comment]
> Can you tell me which browser, device and operative system are you using? I can't reproduce without that info. My own systems seem to work fine

Are there any developments regarding this issue?

**Comment by Eskuero** [comment]
I couldn't reproduce the issue in any browser in Windows 10. All of them downloaded a image as expected. Can you please upload the file that it downloads?

Also do the following:
1. Open a new browser tab.
2. Press Ctrl+Alt+J (That should open a small console on the side of the bottom)
3. On the same tab open the tier list generator.
4. Then refresh it using Ctrl+F5
5. Now try to download the tier list again.
6. Make a screenshot or copy and paste any logging and debugging text that appeared on the console and post it here.

**Comment by gunchapred** [comment]
> I couldn't reproduce the issue in any browser in Windows 10. All of them downloaded a image as expected. Can you please upload the file that it downloads?
> 
> Also do the following:
> 
> 1. Open a new browser tab.
> 2. Press Ctrl+Alt+J (That should open a small console on the side or the bottom)
> 3. On the same tab open the tier list generator.
> 4. Then refresh it using Ctrl+F5
> 5. Now try to download the tier list again.
> 6. Make a screenshot or copy and paste any logging and debugging text that appeared on the console and post it here.

![image](https://user-images.githubusercontent.com/56003719/150806754-5756c2bc-e9a3-4eaf-86b8-fa449e12ee5e.png)

This was what I got.

**Comment by Eskuero** [comment]
dammit, chrome disables by default certain loggings. On that screenshot you showed me there's a drop-down with the text "Default levels", open it and make sure Verbose, Info, Warnings and Errors are all checked, then try again.

Also you didn't upload the text file that it provides.

**Comment by gunchapred** [comment]
![image](https://user-images.githubusercontent.com/56003719/150983481-55e9da01-88cb-40e8-a95d-1337f5305092.png)

![image](https://user-images.githubusercontent.com/56003719/150983536-9126357a-2c55-4724-8a7f-b57024de107e.png)

![image](https://user-images.githubusercontent.com/56003719/150983595-181696e7-8139-40b9-8ce3-833073167131.png)

![image](https://user-images.githubusercontent.com/56003719/150983639-31d7a8a9-723e-4fc9-83cf-bf45ac6aa05c.png)

![image](https://user-images.githubusercontent.com/56003719/150983693-fbaa7bf8-b2f9-4303-9833-e0faa88721b1.png)

![image](https://user-images.githubusercontent.com/56003719/150983761-5b22cacd-9e07-4881-9d57-2f97bd39d2e4.png)

![image](https://user-images.githubusercontent.com/56003719/150983833-c0a7b876-9784-4c99-a46a-709fad6d6e9c.png)

![image](https://user-images.githubusercontent.com/56003719/150983921-8bd27503-57a6-4fe2-bbc0-601ee5cd10a7.png)

![image](https://user-images.githubusercontent.com/56003719/150983985-bd88ad9f-a2de-476b-93ab-bfdd8d04632e.png)


Ok, here's all the screenshots right here. And I can't send you the text file because it's empty. Github doesn't allow that.

**Comment by gunchapred** [comment]
> dammit, chrome disables by default certain loggings. On that screenshot you showed me there's a drop-down with the text "Default levels", open it and make sure Verbose, Info, Warnings and Errors are all checked, then try again.
> 
> Also you didn't upload the text file that it provides.

Anything you can get from all of this?

**Comment by Eskuero** [comment]
Sadly no, does it fail as well in other browsers?

**Comment by gunchapred** [comment]
> Sadly no, does it fail as well in other browsers?

Edge seems to work, though I'd need to build my tier list back up from scratch all over again.

**Comment by gunchapred** [comment]
> Sadly no, does it fail as well in other browsers?

Any updates on this? I can confirm that I'm still experiencing this bug on Chrome. If it helps, this is the tier list I've been using when this bug occurred. Though this bug happens regardless of the tier list I make.

![Tier List (1)](https://user-images.githubusercontent.com/56003719/151709333-35b75b25-8212-4af9-9c95-11c670b4b93d.png)

**Comment by gunchapred** [comment]
Update: Tier list generator now has this issue on Edge as well, and I think one of my extensions is the issue.

**Comment by gunchapred** [comment]
Figured it out. Grammarly apparently is incompatible with the Tier List Generator.

**Comment by Eskuero** [comment]
Thanks for figuring it out. Yeah sometimes extensions interact in weird ways with webpages. Will leave this open and take a look at the extension to see if it's something I could patch easily, but most likely not

**Comment by Eskuero** [comment]
I can't see what to about it. Sorry.
