### ISSUE TITLE
Tier List Generator Doesn't Save Second Tier List

### ISSUE THREAD

**Issue by gunchapred** [Eskuero/fehbuilder#9]
Steps To Reproduce:

Go to the tier list editor.
Make a tier list.
Click Save
Create A New Tier List that isn't in the default spot.
Click Save Again and make sure it's saved to the correct spot.
Close the page.
Go back to the page
Load the tier list that isn't in the Default spot.

Once done, you will find that the tiers are cleared, but not only are they not filled with the tier list that was thee, but the tiers renamed in the default list will not change to what they are in the new list.

Expected Outcome: If you save a tier list in a spot that isn't default, it should still be there the next time you load it up

**Comment by Eskuero** [comment]
I can't reproduce this at all with the steps provided so we are either having different expectations or different experiences. Please upload a video following your own steps starting from a refresh of the page so I can review it better.

**Comment by gunchapred** [comment]
> I can't reproduce this at all with the steps provided so we are either having different expectations or different experiences. Please upload a video following your own steps starting from a refresh of the page so I can review it better.

https://user-images.githubusercontent.com/56003719/153623826-4d841420-4126-4eb4-a051-b3cf5f420240.mp4

Attached here is a video demonstrating the bug.

**Comment by Eskuero** [comment]
Can you do while keeping the console open to see if any errors are output when saving? You open it with Ctrl+Alt+J.
So basically:
1. Start recording
2. Open the console (Ctrl+Alt+J)
3. Edit the tier and save it.
4. Run this command in the open terminal
`localStorage.getItem('saves')`
5. Refresh the tab (there's no need to open another one)
6. Type again the command from step 4.
7. Try reloading it.

Additional question: Modifications on the "Default" tierlist are properly saved?

**Comment by gunchapred** [comment]
> Can you do while keeping the console open to see if any errors are output when saving? You open it with Ctrl+Alt+J. So basically:
> 
> 1. Start recording
> 2. Open the console (Ctrl+Alt+J)
> 3. Edit the tier and save it.
> 4. Run this command in the open terminal
>    `localStorage.getItem('saves')`
> 5. Refresh the tab (there's no need to open another one)
> 6. Type again the command from step 4.
> 7. Try reloading it the affected tier again.
> 
> Additional question: Modifications on the "Default" tierlist are properly saved?

Yes, the default tier list loads and saves correctly. I had been using it to keep track of my merge projects for some time.

[2022-02-11_14-39-25.zip](https://github.com/Eskuero/fehbuilder/files/8051238/2022-02-11_14-39-25.zip)

Here's the video as requested.

**Comment by Eskuero** [comment]
What is failing is a certain function used to detect the used color before storing the new data. I can't identify why tho but I think I might have a workaround for it. Will tell you to test when it's deployed.

**Comment by gunchapred** [comment]
> What is failing is a certain function used to detect the used color before storing the new data. I can't identify why tho but I think I might have a workaround for it. Will tell you to test when it's deployed.

Gotcha

**Comment by Eskuero** [comment]
Try if it works now. Make sure you refresh the webpage with Ctrl+F5 to avoid old cached code from your browser of getting in your way.

**Comment by gunchapred** [comment]
> Try if it works now. Make sure you refresh the webpage with Ctrl+F5 to avoid old cached code from your browser of getting in your way.

Works like a charm, thanks.

**Comment by gunchapred** [comment]
> Confirmed fixed in [8055eb24d122d249ef1a0a500fb1eda0a400e7a4](https://github.com/Eskuero/fehbuilder/commit/8055eb24d122d249ef1a0a500fb1eda0a400e7a4)

Though I would like to an addendum here, I can only save once per refresh. Afterwards, I have to refresh the page to save the tier list again.

**Comment by gunchapred** [comment]
Actually, I don't know how it works here. Apparently, the bug only made it past my testing, and my actual attempt to use it.

![image](https://user-images.githubusercontent.com/56003719/153689300-e821c44e-5126-47e4-a9eb-7d2a852c0bc6.png)

Here's the new bug.
